### ISSUE TITLE
feature request: add time.Time and few other changes

### ISSUE THREAD

**Issue by pdemacs** [m-zajac/json2go#4]
1. Please see if it is possible to support time.Time for dates.
2. Option to not sort golang struct alphabatically basically preserving the json appearance of fields in golang struct.
Excellent tool btw

**Comment by m-zajac** [comment]
1. Great idea. Could you provide an example (multiple examples would be great) of attribute with a time?
2. I think this is not possible using standard json package. It returns maps, which inherently don't preserve order. If you have some idea how to do this, please share :)

**Comment by pdemacs** [comment]
1. Here is one from the github api
createdAt/closedAt/authoredDate etc. can be of type time.Time .  If we paste this data into https://mholt.github.io/json-to-go/ it is able to give the structure correctly . Background of this request is in almost any graphql schema we can find something of type date and the json generated would contain date as field converting it to go struct requirese manual copying/pasting from string to time.Time which is error prone.
{
            "id": "MDExOlB1bGxSZXF1ZXN0NDk0MDAyMDg3",
            "createdAt": "2020-09-28T09:13:40Z",
            "closedAt": "2020-09-28T10:18:13Z",
            "updatedAt": "2020-09-28T10:18:14Z",
            "mergedAt": "2020-09-28T10:18:13Z",
            "publishedAt": "2020-09-28T09:13:40Z",
            "number": 31772,
            "title": "_variables: change $btn-close-bg's attribute order",
            "state": "MERGED",
            "reviewDecision": "APPROVED",
            "isDraft": false,
            "headRefName": "XhmikosR-patch-3",
            "author": {
              "login": "XhmikosR"
            },
            "mergedBy": {
              "login": "XhmikosR"
            },
            "labels": {
              "edges": [
                {
                  "node": {
                    "name": "css"
                  }
                },
                {
                  "node": {
                    "name": "v5"
                  }
                }
              ]
            },
            "files": {
              "edges": [
                {
                  "node": {
                    "additions": 1,
                    "deletions": 1,
                    "path": "scss/_variables.scss"
                  }
                }
              ],
              "pageInfo": {
                "endCursor": "MQ",
                "hasNextPage": false
              }
            },
            "reviews": {
              "edges": [
                {
                  "node": {
                    "author": {
                      "login": "MartijnCuppens"
                    },
                    "submittedAt": "2020-09-28T09:59:39Z",
                    "publishedAt": "2020-09-28T09:59:39Z",
                    "state": "APPROVED",
                    "commit": {
                      "id": "MDY6Q29tbWl0MjEyNjI0NDo4ZTYxMTI0Yjk5NzhjM2EwNGE0ZjkyM2YwYTVjZDk5MGNiYzY3YjVi"
                    }
                  }
                }
              ],
              "pageInfo": {
                "endCursor": "Y3Vyc29yOnYyOpO5MjAyMC0wOS0yOFQxNToyOTozOSswNTozMLkyMDIwLTA5LTI4VDE1OjI5OjM5KzA1OjMwzh2lJzY=",
                "hasNextPage": false
              }
            },
            "commits": {
              "edges": [
                {
                  "node": {
                    "commit": {
                      "id": "MDY6Q29tbWl0MjEyNjI0NDo4ZTYxMTI0Yjk5NzhjM2EwNGE0ZjkyM2YwYTVjZDk5MGNiYzY3YjVi",
                      "authoredDate": "2020-09-28T09:09:35Z",
                      "committedDate": "2020-09-28T09:09:35Z",
                      "pushedDate": "2020-09-28T09:10:36Z"
                    }
                  }
                },
                {
                  "node": {
                    "commit": {
                      "id": "MDY6Q29tbWl0MjEyNjI0NDo5MTE1ZTQyMDc0YWUyODg4ZDY5ZmU3ZDJmYjRmNWJhYmMwYmZiYzEx",
                      "authoredDate": "2020-09-28T10:14:42Z",
                      "committedDate": "2020-09-28T10:14:42Z",
                      "pushedDate": "2020-09-28T10:15:51Z"
                    }
                  }
                }
              ],
              "pageInfo": {
                "hasNextPage": false,
                "endCursor": "Mg"
              }
            },
            "comments": {
              "edges": [],
              "pageInfo": {
                "hasNextPage": false,
                "endCursor": null
              }
            },
            "timelineItems": {
              "nodes": [
                {
                  "id": "MDIwOlJldmlld1JlcXVlc3RlZEV2ZW50MzgxMzQ4MzE3OQ==",
                  "createdAt": "2020-09-28T09:13:40Z",
                  "actor": {
                    "login": "XhmikosR"
                  },
                  "requestedReviewer": null
                }
              ]
            }
          }
2. Ok, I have not digged into the code, i don't have much idea on how to do this. If i come across something i will update it here.

**Comment by m-zajac** [comment]
Thanks for example. I'll do it when I have some spare time.

**Comment by m-zajac** [comment]
Fixed in v1.1.0. Let me know if everything works ok.

**Comment by pdemacs** [comment]
LGTM
