### ISSUE TITLE
Incorrect struct type

### ISSUE THREAD

**Issue by Codinee** [m-zajac/json2go#9]
The struct type is incorrectly created for the newly created datatype. The newly datatype is created as an array struct when one of the extractable substructure is an array at one place and non-array in other.
 
Input 
		`{"starttime":"2021-03-10T08:04:05Z",
  "endtime":"2021-03-10T15:04:05Z",
  "details":
 [{"state":"working",
   "duration":25
 },
 {"state":"idle",
   "duration":15
 },
 {"state":"working",
   "duration":20
 }]
 }`,
		`{"starttime":"2021-03-10T08:04:05Z",
  "endtime":"2021-03-10T15:04:05Z",
  "totalwork":
  {"state":"working",
   "duration":25
 }
 }`,

Ouput 
**Expected** 
type Document struct {
        Details   []DurationState `json:"details,omitempty"`
        Endtime   time.Time       `json:"endtime"`
        Starttime time.Time       `json:"starttime"`
        Totalwork *DurationState  `json:"totalwork,omitempty"`
}
type DurationState struct {
        Duration int    `json:"duration"`
        State    string `json:"state"`
}

**Actual** 
type Document struct {
        Details   []DurationState `json:"details,omitempty"`
        Endtime   time.Time       `json:"endtime"`
        Starttime time.Time       `json:"starttime"`
        Totalwork *DurationState  `json:"totalwork,omitempty"`
}
type DurationState []struct {
        Duration int    `json:"duration"`
        State    string `json:"state"`
}

Here the DurationState is created as an array struct when it should just be a struct. 

I am willing to provide a PR for this issue with fix. Please let me know.

**Comment by m-zajac** [comment]
@Codinee great catch, thank you for raising this issue. I'll fix it soon and let you know.

**Comment by m-zajac** [comment]
@Codinee fixed. If you found any other problems please let me know :) Thanks again.
